x1 = linspace(0,power(10,9),65000000);
y1 = arrayfun(@(x) abs((exp(1) - power((1 + (1/x)), x)))/abs(exp(1)), x1);
p1 = semilogy(x1, y1);
xlabel('n');
ylabel('relative approximation error');
title('relative approximation error of e using (1 + 1/n)^n for increasing values of n');
x2 = power(2, 0:100);
y2 = arrayfun(@(x) abs((exp(1) - power((1 + (1/x)), x))), x2);
p2 = semilogy(log2(x2),y2);
xlabel('2^k');
ylabel('absolute approximation error');
title('absolute approximation error of e using (1 + 1/n)^n for increasing powers of 2');